name: build and publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    # publish container image to docker hub

    - name: DOCKER HUB login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: build and publish container image to DOCKER HUB
      run: |
        docker build . -t xtensive/smart-reductor:${{ github.event.release.tag_name }} -t xtensive/smart-reductor
        docker push xtensive/smart-reductor:${{ github.event.release.tag_name }}
        docker push xtensive/smart-reductor:latest